import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/layout/Header";

export const metadata: Metadata = {
  title: "Jay's Portfolio",
  description: "Generated by Jay",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`font-mira antialiased`}
      >
        <Header/>
        {children}
      </body>
    </html>
  );
}
